### ISSUE TITLE
java.lang.NoSuchMethodError: java.lang.String.isEmpty

### ISSUE THREAD

**Issue by pilhuhn** [pilhuhn/ZwitscherA#168]
``` bash
java.lang.NoSuchMethodError: java.lang.String.isEmpty
at de.bsd.zwitscher.TabWidget.onCreate(TabWidget.java:66)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
at android.app.ActivityThread.access$2300(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4735)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by DHuckaby** [comment]
Fyi, this was added in 2.3. For < 2.3 support use something like .length() == 0, or TextUtils.isEmpty()

**Comment by pilhuhn** [comment]
@DHuckaby Yeah. It is hard on the verge of Java 8 to remember that Android 2.2 is basically still Java 5 and the others are Java 6
